# typed: false
# frozen_string_literal: true

# This file was generated by cargo-dist.
# Do not modify this file manually.

cask "dtop" do
  version "0.6.10"

  on_intel do
    on_macos do
      url "https://github.com/amir20/dtop/releases/download/v0.6.10/dtop-x86_64-apple-darwin.tar.gz"
      sha256 "d675e382b5aa9dbce97f7dee7c6aeb97e6d620e5437c4b01e08dc3d2efa365ca"
    end
    on_linux do
      url "https://github.com/amir20/dtop/releases/download/v0.6.10/dtop-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "41e43ba6e7f635ae0cc996aa3b0184f9c585728af6ca70e79bad1594c17ba7dc"
    end
  end

  on_arm do
    on_macos do
      url "https://github.com/amir20/dtop/releases/download/v0.6.10/dtop-aarch64-apple-darwin.tar.gz"
      sha256 "0e426622eb13e3c7d8ddbca785129d485f8697c739f7709a690334c3bb1c8edb"
    end
    on_linux do
      url "https://github.com/amir20/dtop/releases/download/v0.6.10/dtop-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a9ea40b614aa1d54bef26c9042e430d5b2f5f825907b0911f8f3e6cb33d6ba27"
    end
  end

  name "dtop"
  desc "A terminal-based Docker container monitoring tool"
  homepage "https://github.com/amir20/dtop"

  on_intel do
    on_macos do
      binary "dtop-x86_64-apple-darwin/dtop"

      postflight do
        system_command "/usr/bin/xattr",
                      args: ["-d", "com.apple.quarantine", "#{staged_path}/dtop-x86_64-apple-darwin/dtop"],
                      must_succeed: false
      end
    end
    on_linux do
      binary "dtop-x86_64-unknown-linux-gnu/dtop"
    end
  end

  on_arm do
    on_macos do
      binary "dtop-aarch64-apple-darwin/dtop"

      postflight do
        system_command "/usr/bin/xattr",
                      args: ["-d", "com.apple.quarantine", "#{staged_path}/dtop-aarch64-apple-darwin/dtop"],
                      must_succeed: false
      end
    end
    on_linux do
      binary "dtop-aarch64-unknown-linux-gnu/dtop"
    end
  end
end
