# typed: false
# frozen_string_literal: true

# This file was generated by cargo-dist.
# Do not modify this file manually.

cask "dtop" do
  version "0.6.3"

  on_intel do
    on_macos do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-x86_64-apple-darwin.tar.gz"
      sha256 "51246f4f14c490360eebcdf5de32f2bda4a65bd0847f6723525e41e601eba625"
    end
    on_linux do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "616b498a23517f43b0ea49ffb11ecd0342008e46fe782a209a1971abd46d8b00"
    end
  end

  on_arm do
    on_macos do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-aarch64-apple-darwin.tar.gz"
      sha256 "539861a0db3d79d6b950c1debcb42ab1ab342be2411cfadb4f0f5de1ece64cb9"
    end
    on_linux do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ba7724d7be7bc1724fef0e41d1c553c36c6051eef292629b4e4b5cc0b73bddb7"
    end
  end

  name "dtop"
  desc "A terminal-based Docker container monitoring tool"
  homepage "https://github.com/amir20/dtop"

  on_intel do
    on_macos do
      binary "dtop-x86_64-apple-darwin/dtop"

      postflight do
        system_command "/usr/bin/xattr",
                      args: ["-d", "com.apple.quarantine", "#{staged_path}/dtop-x86_64-apple-darwin/dtop"],
                      must_succeed: false
      end
    end
    on_linux do
      binary "dtop-x86_64-unknown-linux-gnu/dtop"
    end
  end

  on_arm do
    on_macos do
      binary "dtop-aarch64-apple-darwin/dtop"

      postflight do
        system_command "/usr/bin/xattr",
                      args: ["-d", "com.apple.quarantine", "#{staged_path}/dtop-aarch64-apple-darwin/dtop"],
                      must_succeed: false
      end
    end
    on_linux do
      binary "dtop-aarch64-unknown-linux-gnu/dtop"
    end
  end
end
