# typed: false
# frozen_string_literal: true

# This file was generated by cargo-dist.
# Do not modify this file manually.

cask "dtop" do
  version "0.6.0"

  on_intel do
    on_macos do
      url "https://github.com/amir20/dtop/releases/download/v0.6.0/dtop-x86_64-apple-darwin.tar.gz"
      sha256 "31d6eca6088a62a3d220b53c8a7d3813958bec80008e97f1bf3200a59b75cd99"
    end
    on_linux do
      url "https://github.com/amir20/dtop/releases/download/v0.6.0/dtop-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "680d36114cbd551163977ef4e3acff7a601236b21b0f368b8d903c6ea9630059"
    end
  end

  on_arm do
    on_macos do
      url "https://github.com/amir20/dtop/releases/download/v0.6.0/dtop-aarch64-apple-darwin.tar.gz"
      sha256 "31a3f97c3c48bf490a041207e7d660d2fa7a1dd0d336b7e9545a9b3dc811597b"
    end
    on_linux do
      url "https://github.com/amir20/dtop/releases/download/v0.6.0/dtop-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1759c1b7ad17070ab8c9bfd47631934fc3f3c5531356c7464e7952b1cff8f455"
    end
  end

  name "dtop"
  desc "A terminal-based Docker container monitoring tool"
  homepage "https://github.com/amir20/dtop"

  on_intel do
    on_macos do
      binary "dtop-x86_64-apple-darwin/dtop"
    end
    on_linux do
      binary "dtop-x86_64-unknown-linux-gnu/dtop"
    end
  end

  on_arm do
    on_macos do
      binary "dtop-aarch64-apple-darwin/dtop"
    end
    on_linux do
      binary "dtop-aarch64-unknown-linux-gnu/dtop"
    end
  end
end
