# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtop < Formula
  desc "dtop - A top-like tool for Docker containers"
  homepage "https://github.com/amir20/dtop"
  version "0.0.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amir20/dtop/releases/download/v0.0.27/dtop_darwin_x86_64.tar.gz"
      sha256 "5c5f74d5323e521659f451288d22e45939af0f011bf70e7baa140532436b8f5f"

      def install
        bin.install "dtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amir20/dtop/releases/download/v0.0.27/dtop_darwin_arm64.tar.gz"
      sha256 "b29fc50a712c250dee203c6a9430c0d83d3100b782a4ce3ea910549e8692dd7d"

      def install
        bin.install "dtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/amir20/dtop/releases/download/v0.0.27/dtop_linux_x86_64.tar.gz"
      sha256 "5f0866fa51a9df5a013a7878d5c4e45d1ad684104bd27ce57df0c3bc309d4a96"
      def install
        bin.install "dtop"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/amir20/dtop/releases/download/v0.0.27/dtop_linux_armv6.tar.gz"
      sha256 "965cd59c80d319608fd0e8f8e30d57f251474b1610f304219e69f19578bdb802"
      def install
        bin.install "dtop"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/amir20/dtop/releases/download/v0.0.27/dtop_linux_arm64.tar.gz"
      sha256 "1ad28b859a209a8cdc870081e5580acc63fffdea7283edd943c285789d9a93ba"
      def install
        bin.install "dtop"
      end
    end
  end
end
