# typed: false
# frozen_string_literal: true

# This file was generated by cargo-dist.
# Do not modify this file manually.

class Dtop < Formula
  desc "Terminal-based Docker container monitoring tool"
  homepage "https://github.com/amir20/dtop"
  version "0.6.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-x86_64-apple-darwin.tar.gz"
      sha256 "51246f4f14c490360eebcdf5de32f2bda4a65bd0847f6723525e41e601eba625"

      def install
        bin.install "dtop"
      end
    end
    on_arm do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-aarch64-apple-darwin.tar.gz"
      sha256 "539861a0db3d79d6b950c1debcb42ab1ab342be2411cfadb4f0f5de1ece64cb9"

      def install
        bin.install "dtop"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "616b498a23517f43b0ea49ffb11ecd0342008e46fe782a209a1971abd46d8b00"

      def install
        bin.install "dtop"
      end
    end
    on_arm do
      url "https://github.com/amir20/dtop/releases/download/v0.6.3/dtop-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ba7724d7be7bc1724fef0e41d1c553c36c6051eef292629b4e4b5cc0b73bddb7"

      def install
        bin.install "dtop"
      end
    end
  end

  test do
    assert_match "dtop #{version}", shell_output("#{bin}/dtop --version")
  end
end
